site_name: Lautaro • Mobile Security
site_url: https://lautarovculic.github.io
site_description: Mobile Security Writeups - CTF
theme: { name: material, palette: { scheme: slate } custom_dir: overrides }
plugins:
  - search
  - roamlinks
  - rss: { match_path: "writeups/.*" }
  - glightbox
  - minify: { minify_html: true }
docs_dir: docs
